# Generated by Django 5.2rc1 on 2025-04-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='type',
            field=models.CharField(choices=[('double', 'Double'), ('suite', 'Suite'), ('simple', 'Simple')], max_length=50),
        ),
    ]
