# Generated by Django 5.2rc1 on 2025-04-29 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_chambre_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id_facture', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('paypal', 'PayPal'), ('visa', 'Visa'), ('mastercard', 'MasterCard'), ('stripe', 'Stripe')], max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.client')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.reservation')),
            ],
        ),
    ]
