# Generated by Django 5.2rc1 on 2025-05-09 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_facture'),
        ('hotel', 'add_default_passwords'),
    ]

    operations = [
    ]
