# Generated by Django 5.2rc1 on 2025-05-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_reservation_options_reservation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
