# Generated by Django 5.2rc1 on 2025-05-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_facture_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='montant_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
